name: Schemas release PR

on:
  repository_dispatch:
      types: schemas_release

jobs:
  create-pull-request:
      runs-on: ubuntu-18.04
      steps:
        - name: Update schemas version
          uses: actions/checkout@v2
          with:
            ref: 'master'
        - run: |
            TAG="${{ github.event.client_payload.tag }}"
            echo "::set-env name=SCHEMAS_VERSION::$TAG"
            
            # Import GPG key to sign the commit
            echo "${{ secrets.GPG_PRIVATE_KEY }}" | base64 --decode | gpg --import --no-tty --batch --yes &>/dev/null
            
            # Update Git user to match gpg key
            git config user.name "${{ secrets.GIT_USER_NAME }}"
            git config user.email "${{ secrets.GIT_USER_EMAIL }}"
            
            # Set Git GPG program and signing key
            git config --global gpg.program $(which gpg)
            git config --global user.signingkey "${{ secrets.GPG_KEY_ID }}"
            
            # Update & commit schema version file
            echo $TAG > .schemas-version
            git add -A
            git commit -S -m "Update schema version to $TAG"
        - name: Create Pull Request
          uses: peter-evans/create-pull-request@v2
          with:
            token: "${{ secrets.GITHUB_TOKEN }}"
            committer: "${{ secrets.GIT_USER_NAME }} <${{ secrets.GIT_USER_EMAIL }}>"
            author: "${{ secrets.GIT_USER_NAME }} <${{ secrets.GIT_USER_MAIL }}>"
            commit-message: "Update schemas to version ${{ env.SCHEMAS_VERSION }}"
            title: "Update schemas to version ${{ env.SCHEMAS_VERSION }}"
            body: |
              This is an auto-generated PR.
              Schema release: https://github.com/ONSdigital/eq-questionnaire-schemas/releases/tag/${{ env.SCHEMAS_VERSION }}
            branch: "schemas-release-${{ env.SCHEMAS_VERSION }}"
        - name: Temp
          uses: actions/checkout@v2
        - run: |
            exit 1
